name: Deploy Mail Worker

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Deploy to server
              run: |
                cd /home/ubuntu
                ./deploy_worker.sh
