name: Deploy Mail Worker

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted

        env:
            DEPLOY_PATH: "/home/ubuntu/Mail-Worker"

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Ensure Repository Exists
              run: |
                if [ ! -d "$DEPLOY_PATH" ]; then
                    git clone https://github.com/SymonMuchemi/Mail-Worker.git $DEPLOY_PATH
                fi
            
            - name: Stop and remove existing containers
              run: |
                cd $DEPLOY_PATH
                sudo docker-compose down || true
          
            - name: Pull latest changes
              run: |
                cd $DEPLOY_PATH
                git pull origin main
            
            - name: Build and start containers
              run: |
                cd $DEPLOY_PATH
                sudo docker-compose up --build -d
